definitions:
  default: &default
    min_log_level: info
    app_name: realapp
    log_dir: logs
    secure_mode: false
configurations:
  dev: *default
  qa: *default
  production: *default

# 객체에 앵커와 별칭 사용하기